// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDML3Oj7JyDtpe3HnlWMskyzLWK1J5WG7M',
    appId: '1:850892090964:web:97a44d338b271deb8f47c1',
    messagingSenderId: '850892090964',
    projectId: 'abm4-laminate-app',
    authDomain: 'abm4-laminate-app.firebaseapp.com',
    storageBucket: 'abm4-laminate-app.firebasestorage.app',
    measurementId: 'G-D11PHBHFMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7QrqSli113mozJzkteen6CHTf7Y2Tvo',
    appId: '1:850892090964:android:20470fca8a6ea1ae8f47c1',
    messagingSenderId: '850892090964',
    projectId: 'abm4-laminate-app',
    storageBucket: 'abm4-laminate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYIfJ1ZXnOliCgteNYWbLqV2pIydGw40',
    appId: '1:850892090964:ios:3323dadc65bc83af8f47c1',
    messagingSenderId: '850892090964',
    projectId: 'abm4-laminate-app',
    storageBucket: 'abm4-laminate-app.firebasestorage.app',
    iosBundleId: 'com.example.testapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYIfJ1ZXnOliCgteNYWbLqV2pIydGw40',
    appId: '1:850892090964:ios:3323dadc65bc83af8f47c1',
    messagingSenderId: '850892090964',
    projectId: 'abm4-laminate-app',
    storageBucket: 'abm4-laminate-app.firebasestorage.app',
    iosBundleId: 'com.example.testapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDML3Oj7JyDtpe3HnlWMskyzLWK1J5WG7M',
    appId: '1:850892090964:web:5857f263e2eeee7c8f47c1',
    messagingSenderId: '850892090964',
    projectId: 'abm4-laminate-app',
    authDomain: 'abm4-laminate-app.firebaseapp.com',
    storageBucket: 'abm4-laminate-app.firebasestorage.app',
    measurementId: 'G-LWKDPJSCWL',
  );
}
